apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker-2-1-0
  labels:
    app: spark-worker-2-1-0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spark-worker-2-1-0
  template:
    metadata:
      labels:
        app: spark-worker-2-1-0
    spec:
      containers:
      - name: spark-worker-2-1-0
        image: docker.io/rerng007/pipeline:spark_worker
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 2000m
            memory: 2000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: 2g
        - name: SPARK_MASTER
          value: spark://spark-master-2-1-0:7077
        ports:
        - containerPort: 6061
