apiVersion: v1 
kind: Service
metadata:
  name: spark-client
  labels:
    app: spark-client
spec:
  type: LoadBalancer
  ports:
  - name: spark-client
    port: 80 
    targetPort: 8754
  - name: spark-client-api-proxy
    port: 81
    targetPort: 8755
  - name: tensorboard
    port: 6006
    targetPort: 6006
  - name: sparkui-app1
    port: 4040
    targetPort: 4040
  selector:
    app: spark-client
