apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: rerng007/pipeline:jupyterhub_authen
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 200Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        - name: JUPYTERHUB_AUTHENTICATOR
          value: dummyauthenticator.DummyAuthenticator 
        - name: JUPYTERHUB_SHARED_PASSWORD 
          value: ""
        - name: OAUTH_CALLBACK_URL
          value: "" 
        - name: GITHUB_CLIENT_ID
          value: ""
        - name: GITHUB_CLIENT_SECRET
          value: ""
        ports:
        - containerPort: 6006
        - containerPort: 8754
        - containerPort: 8755
        volumeMounts:
#          - name: kube-config-secret-volume
#            readOnly: true
#            mountPath: /root/.kube
#          - name: hadoop-conf-dev-volume
#            mountPath: /etc/hadoop/conf
           - name: ebs-volume
             mountPath: /mnt/ebs-volume
           - name: git-volume
             mountPath: /root/volumes
      volumes:
        - name: ebs-volume
          persistentVolumeClaim: 
            claimName: ebs-claim-1
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml"
            # repository: "https://[o-auth-personal-acess-token]:x-oauth-basic@github.com/fluxcapacitor/source.ml.git"
            revision: "master"
